[package]
name = "totp-lite_"
version = "2.2.0"
edition = "2024"
rust-version = "1.85.1"
authors = ["Colin Woodbury <colin@fosskers.ca>", "<github.com/pepa65>"]
description = "A simple, correct TOTP library."
repository = "https://github.com/pepa65/totp-lite"
documentation = "https://docs.rs/totp-lite_/"
readme = "README.md"
license = "MIT"
keywords = ["authentication", "totp", "otp", "2fa"]
categories = ["authentication", "algorithms", "security"]

[lib]
name = "totp_lite"

[[example]]
name = "ga"
path = "examples/ga.rs"

[dependencies]
# All github/RustCrypto crates
digest = "0.11"
hmac = "0.13"
sha1 = "0.11"
sha2 = "0.11"

[dev-dependencies]
# What github/RustCrypto/base32ct depends on
base32 = "1.0.0-rc.1"
